version: "3"
services:
       node-app:
           #container_name: ems-db
           #image: emssmall:4.0
           build: .
           restart: unless-stopped
           ports:
             - '3001:3001'
           links:
             - mongo
       mongo:
         container_name: mongosmall
         image: mongo
         volumes:
           - ./data:/data/db
         ports:
           - '27017:27017'